/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiAnalyzePronunciationRouteImport } from './routes/api/analyze-pronunciation'
import { Route as ApiPublicAnalyticsRouteImport } from './routes/api/public/analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzePronunciationRoute = ApiAnalyzePronunciationRouteImport.update({
  id: '/api/analyze-pronunciation',
  path: '/api/analyze-pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsRoute = ApiPublicAnalyticsRouteImport.update({
  id: '/api/public/analytics',
  path: '/api/public/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-pronunciation': typeof ApiAnalyzePronunciationRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-pronunciation': typeof ApiAnalyzePronunciationRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-pronunciation': typeof ApiAnalyzePronunciationRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/analyze-pronunciation'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/public/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/analyze-pronunciation'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/public/analytics'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/analyze-pronunciation'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/public/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAnalyzePronunciationRoute: typeof ApiAnalyzePronunciationRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicAnalyticsRoute: typeof ApiPublicAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-pronunciation': {
      id: '/api/analyze-pronunciation'
      path: '/api/analyze-pronunciation'
      fullPath: '/api/analyze-pronunciation'
      preLoaderRoute: typeof ApiAnalyzePronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics': {
      id: '/api/public/analytics'
      path: '/api/public/analytics'
      fullPath: '/api/public/analytics'
      preLoaderRoute: typeof ApiPublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAnalyzePronunciationRoute: ApiAnalyzePronunciationRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicAnalyticsRoute: ApiPublicAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
